version: 1.0.{build}

configuration: Debug, Release

platform: x64

shallow_clone: true

clone_folder: C:\Users\marma\.atom\Github\bddsl github io\smiley\smiley

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

dotnet_csproj:

  patch: true

  file: '**\*.csproj'

  version: '{version}'

  package_version: '{version}'

  assembly_version: '{version}'

  file_version: '{version}'

  informational_version: '{version}'

environment:

  OneDrive: C:\Users\marma\OneDrive - DslBd

services: iis

nuget:

  account_feed: true

  project_feed: true

build:

  publish_wap: true

  publish_azure: true

  publish_nuget: true

  publish_nuget_symbols: true

  use_snupkg_format: true

  include_nuget_references: true

  publish_core_console: true

  parallel: true

  verbosity: minimal

test:

  categories:

  - []

notifications:

- provider: GitHubPullRequest

  auth_token:

    secure: UJarN5l4PcAJHhSE8OUZ1H4sYPVzv/yhHdUVTX0MWmnLtaZ2v72MGaLnfNEm1xDC

  on_build_success: true

  on_build_failure: false

  on_build_status_changed: false

- provider: Webhook

  url: https://ci.appveyor.com/api/github/webhook?id=kamf8dklqak957a5

  method: POST

  headers:

    Request URL: https

    Request method: POST

    content-type: application/x-www-form-urlencoded

    Expect: ''

    User-Agent: GitHub-Hookshot/81d186e

    X-GitHub-Delivery: 31ffa3d0-93bd-11e9-89ca-618c35a4a3a4

    X-GitHub-Event: watch

  on_build_success: true

  on_build_failure: false

  on_build_status_changed: false
